//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka_uyg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesaplar
    {
        public int HesapID { get; set; }
        public string MusteriTc { get; set; }
        public string HesapNo { get; set; }
        public decimal Bakiye { get; set; }
        public int EkNumara { get; set; }
        public bool HesapDurum { get; set; }
        public string Kanal { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
