//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka_uyg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kredi
    {
        public int KrediId { get; set; }
        public decimal KrediTutar { get; set; }
        public bool KrediDurum { get; set; }
        public string MusteriId { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
