//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka_uyg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Virman
    {
        public int VirmanId { get; set; }
        public decimal Miktar { get; set; }
        public string GidenHesapNo { get; set; }
        public string GelenHesapNo { get; set; }
        public string MusteriId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Kanal { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
